name: Cathedral Orchestrator
slug: cathedral_orchestrator
description: OpenAI relay + MPC server (non-tools) for Cathedral. Routes to LM Studio & Chroma.
version: "1.0.0"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
hassio_api: true
homeassistant_api: true
ports:
  8001/tcp: 8001
  5005/tcp: 5005
map:
  - ssl
  - share
options:
  lm_hosts:
    default: "http://192.168.1.71:1234"
  chroma_mode: "http"
  chroma_url: "http://192.168.1.71:8000"
  collection_name: "cathedral"
  route_assist: true
  allowed_domains:
    - light
    - switch
    - scene
  log_level: "INFO"
  temperature: 0.7
  top_p: 0.9
  memory_infinite: false
  memory_semantic: false
  memory_procedural: false
  require_gpu: true
schema:
  lm_hosts: dict
  chroma_mode: str
  chroma_url: str
  collection_name: str
  route_assist: bool
  allowed_domains:
    - str
  log_level: str
  temperature: float
  top_p: float
  memory_infinite: bool
  memory_semantic: bool
  memory_procedural: bool
  require_gpu: bool
