name: Cathedral Orchestrator
slug: cathedral_orchestrator
description: OpenAI-compatible relay + MPC server for Cathedral
version: "1.1.15"
arch:
  - amd64
startup: application
boot: auto
init: false
hassio_api: true
ports:
  8001/tcp: 8001
  5005/tcp: 5005
map:
  - ssl
  - share

options:
  lm_hosts:
    - "http://192.168.1.233:1234"          # base of LM Studio, no /v1
  chroma_mode: "http"                       # HTTP only; embedded mode removed
  chroma_url: "http://192.168.1.42:8000"    # used when chroma_mode = http
  chroma_persist_dir: "/data/chroma"        # legacy; ignored in HTTP mode
  collection_name: "cathedral"
  allowed_domains: ["light","switch","scene"]
  temperature: 0.7
  top_p: 0.9
  upserts_enabled: true
  auto_config: true
  auto_discovery: false
  lock_hosts: false
  lock_LMSTUDIO_BASE_PATH: false
  lock_EMBEDDING_BASE_PATH: false
  lock_CHROMA_URL: false
  lock_VECTOR_DB: false

schema:
  lm_hosts:
    - url
  chroma_mode: str
  chroma_url: str?
  chroma_persist_dir: str?
  collection_name: str
  allowed_domains:
    - str
  temperature: float
  top_p: float
  upserts_enabled: bool
  auto_config: bool  # default true
  auto_discovery: bool
  lock_hosts: bool
  lock_LMSTUDIO_BASE_PATH: bool
  lock_EMBEDDING_BASE_PATH: bool
  lock_CHROMA_URL: bool
  lock_VECTOR_DB: bool
