name: Cathedral Orchestrator
slug: cathedral_orchestrator
description: OpenAI-compatible relay + MPC server for Cathedral
version: "0.1.2"
arch:
  - amd64
startup: application
boot: auto
hassio_api: true
ports:
  8001/tcp: 8001
  5005/tcp: 5005
map:
  - ssl
  - share

options:
  lm_hosts:
    - http://192.168.1.233:1234
  chroma_mode: "http"                 # or "embedded"
  chroma_url: "http://192.168.1.42:8000"
  chroma_persist_dir: "/data/chroma"
  collection_name: "cathedral"
  allowed_domains:
    - light
    - switch
    - scene
  temperature: 0.7
  top_p: 0.9
  upserts_enabled: true

schema:
  lm_hosts: list(url)
  chroma_mode: str
  chroma_url: str?
  chroma_persist_dir: str?
  collection_name: str
  allowed_domains:
    - str
  temperature: float
  top_p: float
  upserts_enabled: bool
