name: Cathedral Orchestrator
version: "0.2.3"
slug: cathedral_orchestrator
description: OpenAI-compatible relay and MPC server for Cathedral. Streams chat, routes sessions, and writes vectors to a single LAN Chroma.
arch:
  - amd64
startup: application
boot: auto
init: false
url: https://github.com/SpardaKnight/cathedral_mpc_server_mvp
watchdog: tcp://[HOST]:[PORT:8001]
ports:
  "8001/tcp": 8001
  "5005/tcp": 5005
ports_description:
  "8001/tcp": OpenAI relay and admin API
  "5005/tcp": MPC WebSocket
hassio_api: true
homeassistant_api: true
map:
  - data

# Default options users see
options:
  lm_hosts: []
  chroma_mode: "http"
  chroma_url: "http://127.0.0.1:8000"
  collection_name: "cathedral"
  allowed_domains: [light, switch, scene]
  temperature: 0.7
  top_p: 0.9
  upserts_enabled: true
  auto_config: true
  auto_discovery: false
  lock_hosts: false
  lock_LMSTUDIO_BASE_PATH: false
  lock_EMBEDDING_BASE_PATH: false
  lock_CHROMA_URL: false
  lock_VECTOR_DB: false
  auto_config_active: false
  upserts_active: false

# Schema validator
schema:
  lm_hosts: [url]
  chroma_mode: str
  chroma_url: "url?"
  collection_name: str
  allowed_domains: [str]
  temperature: float
  top_p: float
  upserts_enabled: bool
  auto_config: bool
  auto_discovery: bool
  lock_hosts: bool
  lock_LMSTUDIO_BASE_PATH: bool
  lock_EMBEDDING_BASE_PATH: bool
  lock_CHROMA_URL: bool
  lock_VECTOR_DB: bool
  auto_config_active: bool
  upserts_active: bool
